### ISSUE TITLE
I would like to be a member at large

### ISSUE THREAD

**Issue by EyesUpHigh** [DoD-Platform-One/P1TOC#1]
I am a member of the 309th SWEG

**Comment by andrewsgreene** [comment]
Thanks for the issue, we are picking this back up and hope to have movement very soon.

**Comment by andrewsgreene** [comment]
@EyesUpHigh Might we have the pleasure of knowing your name :) I'm compiling a list of community nominee's, which you'd be included on as a 309th member.

**Comment by andrewsgreene** [comment]
@EyesUpHigh - We've updated issue templates, please submit your interest [HERE](https://github.com/DoD-Platform-One/P1TOC/issues/new?assignees=&labels=community-nomination&template=community-nomination.md&title=Nomination%3A+%5BSamantha+Carter%5D)
