### ISSUE TITLE
Nomination: Barak Stout

### ISSUE THREAD

**Issue by omnipresent07** [DoD-Platform-One/P1TOC#12]
# Nominee
Name:  Barak Stout
GitHub Handle: @barakstout
Organization: 
Employer:  [Raft](http://goraft.tech/)
Bio:
[Barak](https://goraft.tech/about/barak_stout) is a Sr. DevSecOps Engineer with a passion for simplifying complex tasks such as security, testing, developer happiness, and governance using automation. He is laying the foundational work for provisioning open source data products into BigBang using Flux -- starting with Kafka. Additionally, Barak is working on shortening the feedback loops between git push to deployment on [edge using Hardware In the Loop (HIL)](https://github.com/raft-tech/arduino-delivery-container) on BigBang. Finally, he is part of the [Falco Community](https://github.com/falcosecurity/falco), has made Open Source Contributions to [ElasticSearch to fix CVEs](https://github.com/elastic/curator/pull/1582) and [k9s Popeye to report misconfigurations in a live K8s cluster](https://github.com/derailed/popeye/pull/80). Barak is also a CKAD.

## Nominator
Name:  [Bhaarat Sharma](https://goraft.tech/about/bhaarat_sharma) - GitHub Handle: @omnipresent07
Organization:  
Employer: [Raft](http://goraft.tech/)

**Comment by andrewsgreene** [comment]
@omnipresent07 terribly sorry, but we've moved the repo again. Please submit the nomination https://repo1.dso.mil/platform-one/p1toc using the template
