### ISSUE TITLE
Nomination

### ISSUE THREAD

**Issue by anoncam** [DoD-Platform-One/P1TOC#2]
I nominate @ntwkninja and @anoncam for a vacant position in the effort to broaden P1's OSS efforts.

Tagging @jeff-mccoy

**Comment by andrewsgreene** [comment]
Thanks for the issue, we are picking this back up and hope to have movement very soon.

**Comment by anoncam** [comment]
Yay!

**Comment by andrewsgreene** [comment]
@anoncam - we have your nomination for an internal P1 seat. The Chiefs are discussing it and I'll let you know as soon as I do :)
