### ISSUE TITLE
Nomination for vacant seat

### ISSUE THREAD

**Issue by omnipresent07** [DoD-Platform-One/P1TOC#3]
I nominate @barakstout for one of the vacant seats for his efforts to propel the DoD into the future

**Comment by andrewsgreene** [comment]
Thanks for the issue, we are picking this back up and hope to have movement very soon.

**Comment by BarakStout** [comment]
Awesome

**Comment by andrewsgreene** [comment]
@omnipresent07 or @BarakStout - we've updated issue templates, please submit your interest [HERE](https://github.com/DoD-Platform-One/P1TOC/issues/new?assignees=&labels=community-nomination&template=community-nomination.md&title=Nomination%3A+%5BSamantha+Carter%5D)
