### ISSUE TITLE
Commit and Branch Guidelines

### ISSUE THREAD

**Issue by calebhskim** [DoD-Platform-One/P1TOC#4]
For opening a pull request (merge request) are there commit message and branch name standards/guidelines? I didn't see any leads in the repo or wiki. Maybe something similar to [Linux](https://github.com/torvalds/subsurface-for-dirk/blob/a48494d2fbed58c751e9b7e8fbff88582f9b2d02/README#L88) or any other popular linting tool like [commitizen](https://github.com/commitizen/cz-cli) or [commitlint](https://github.com/conventional-changelog/commitlint). Maybe this is documented somewhere and I missed it. Also not sure if there is a proper issue template similar to the project proposal template.

**Comment by andrewsgreene** [comment]
Thanks for the issue, we are picking this back up and hope to have movement very soon.

**Comment by andrewsgreene** [comment]
Thanks @calebhskim. There was an issue with the original issue templates we've created. That has now been updated.

We don't have any guidelines around branch names or commits, we'd love to see what you come up with ;) Submit and issue and pull request if you feel so inclined!
