### ISSUE TITLE
Composable Workflows in PartyBus

### ISSUE THREAD

**Issue by calebhskim** [DoD-Platform-One/P1TOC#5]
[PartyBus](https://p1.dsop.io/#/products/abms-adce) supports a wide variety of technologies within it's environment and toolchain. However, it currently supports only a subset of the listed programming languages and hard codes the workflows. From what I understand, it is a part of the onboarding process to work with the PartyBus/P1 team to properly configure a pipeline specific to your application and tech stack. Ideally your pipeline can plug and play with the existing base configurations but this is not always the case. Additionally it is hard for PartyBus to configure its CI/CD pipeline for every type of tech stack upfront. This becomes an issue and a bottleneck as PartyBus tries to scale and onboard many more teams with varying tech stacks.

I was wondering if it is possible to have community driven, composable CI/CD pipelines, allowing community members to contribute configurations for separate languages and tech stacks. This way PartyBus users can submit build pipelines as they need it, which can in turn be used by future teams and applications. Is this possible? Are there restrictions on how pipelines are approved (submitting hardened images, making sure the correct scans and tools are in place)? Would it be possible to have a guided process where the users do the work upfront and require sign-off from the PartyBus team?

I am not sure if this is the correct format for this request. Also if there is a PartyBus specific committee or a better way to frame this ask please let me know. If possible, I wanted to discuss this idea first before submitting a proposal.

**Comment by andrewsgreene** [comment]
Thanks for the issue, we are picking this back up and hope to have movement very soon.

**Comment by andrewsgreene** [comment]
A small group has been working on this very issue. Soon this group "Autobot" will be presenting their project to the P1TOC. Keep an eye out for the project proposal.

In general, 'self service' pipelines is absolutely a goal. However, the cATO does impose some requirements so we can't tackle 100% composable pipelines.

**Comment by andrewsgreene** [comment]
Please submit an issue against our new location. Thank you. https://repo1.dso.mil/platform-one/p1toc
