### ISSUE TITLE
Vacant Seat Nomination

### ISSUE THREAD

**Issue by braingu-matt** [DoD-Platform-One/P1TOC#8]
I nominate @timgast for one of the vacant seats

**Comment by andrewsgreene** [comment]
@braingu-matt or @timgast - Thanks for your submission, Sorry to change things up. We've updated issue templates, please submit the nomination [HERE](https://github.com/DoD-Platform-One/P1TOC/issues/new?assignees=&labels=community-nomination&template=community-nomination.md&title=Nomination%3A+%5BSamantha+Carter%5D)
